### ISSUE TITLE
Cannot call method of undefined (@auth)

### ISSUE THREAD

**Issue by cintrzyk** [heartsentwined/ember-auth#110]
My app:

```
rails 4
'ember-rails'
'ember-source', '1.0.0'
'ember-data-source', '1.0.0.beta.3'
'ember-auth-rails'
'ember-auth-source'
'ember-auth-module-ember_data-rails'
'ember-auth-module-ember_data-source'
'ember-auth-strategy-token-rails'
'ember-auth-strategy-token-source'
'ember-auth-request-jquery-rails'
'ember-auth-request-jquery-source'
'ember-auth-response-json-rails'
'ember-auth-response-json-source'

"devise", '3.0.3'
```

auth.js.coffee:

```
Dr.Auth = Em.Auth.extend
  modules: ['emberData']
  emberData: 
    userModel: 'user'

  signInEndPoint: '/users/sign_in'
  signOutEndPoint: '/users/sign_out'

  strategy: 'token'
  tokenKey: 'auth_token' 
  tokenLocation: 'param'
  tokenIdKey: 'user_id'

  request: 'jquery'
  response: 'json'
```

In my view I have submit action:

```
submit: (event) ->
  event.preventDefault()
  event.stopPropagation()
  @auth.signIn
    data:
      email:    @get('email')
      password: @get('password')
```

Problem is when I click submit on my form console shows:

```
Uncaught TypeError: Cannot call method 'signIn' of undefined
```

Am I doing something wrong with @auth?
