### ISSUE TITLE
Problem with rememberable

### ISSUE THREAD

**Issue by martinthogersen** [heartsentwined/ember-auth#125]
Hello,

I'm having a problem with rememberable in my application, when I delete my session on the server, and the "ember-auth-rememberable" cookie still has the old auth_token in it's value.

Here's the error I'm getting on init:

```
POST http://localhost:3000/api/v1/sessions => 401 (Unauthorized)
Error while loading route: Object {}
Uncaught #<Object> 
```

How do I fix that? I would like to redirect the user to index.

This is the configuration I'm using:

```
App.Auth = Ember.Auth.extend
  request: 'jquery'
  response: 'json'
  strategy: 'token'
  tokenKey: 'auth_token'
  tokenIdKey: 'user_id'
  tokenLocation: 'authHeader' 
  tokenHeaderKey: 'Token'
  session: 'cookie'
  signInEndPoint: '/api/v1/sessions'
  signOutEndPoint: '/api/v1/sessions'
  modules: ['authRedirectable', 'actionRedirectable', 'emberData']
  authRedirectable:
    route: 'index'
  rememberable: 
    tokenKey: 'remember_token' 
    period: 14 
    autoRecall: true 
  actionRedirectable:
    signOutRoute: 'index'
  emberData: 
    userModel: 'user'
```

My SessionsController on the server sends this result back, when the session token is invalid:

```
render json: { }, status: :unauthorized
```
